"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import ReactMarkdown from "react-markdown";

// Since we don't have a markdown loader set up, we'll store the content here.
const EN_MANUAL = `
# Organizer User Manual

**Role:** Organizer & Staff
**Version:** 1.0
**Date:** 2026-01-26

---

## Chapter 1: Getting Started (Account Setup)

**Context:** The system requires a one-time "Mandatory Onboarding" to link your account to a Player ID for reporting purposes.

1. **Log in via Google**
   *   Click the "Login" button and sign in with your Google Account.

2. **Redirect to Onboarding**
   *   Upon your first login, you will be automatically redirected to the "Welcome to TCG Manager" onboarding page.

3. **Complete Profile**
   *   **First/Last Name:** Confirm your name is correct.
   *   **Pokemon Player ID:** Enter your 7-digit Player ID (required for TDF exports).
   *   **Birth Year:** Select your birth year from the dropdown menu to determine your age division.

4. **Access Dashboard**
   *   Click "Complete Profile". You will be redirected to the main Dashboard where you can manage tournaments.

---

## Chapter 2: Tournament Preparation (Before Round 1)

**Setting up:** Navigate to the specific Tournament Dashboard by selecting your tournament from the home page.

### Roster Management

Use the **Roster Management** card on the right side of the screen to check in players.

1. **Search for Players**
   *   In the "Add New Player" section, type a Name or Player ID into the search bar (e.g., "Pikachu" or "1234567").
   *   Click the Search icon (magnifying glass) or press Enter.

2. **Add Player to Roster**
   *   Find the correct player in the results list. Verify their ID and Birth Year.
   *   Click the **"+" (User Plus)** button next to their name. A success message will appear ("Added [Name] to roster").

3. **Player Not Found**
   *   If the system says "No eligible profiles found," the player may not have created an account or their profile is incomplete.
   *   **Action:** Ask the player to log in and complete the Chapter 1 Onboarding steps on their own device. Once done, search for them again.

---

## Chapter 3: Printing Materials (The Kit)

**The Flyer:** Generate a professional QR Code poster for your venue so players can access pairings and standings instantly.

1. **Access Flyer Page**
   *   On the Tournament Dashboard, click the black button in the top right corner labeled **"Print QR Poster"**.

2. **Print the PDF**
   *   A new page titled "Live Pairings" will open with a large QR code.
   *   Click the **"Print This Page"** button at the top.
   *   *Tip:* Set your printer settings to **A4/Letter size**, **Portrait**, and **Scale 100%**. The header and footer will automatically hide.

---

## Chapter 4: Running the Event (Live Sync)

**The Workflow:** This App visualizes data directly from your TOM (Tournament Operations Manager) software via the TDF file.

### Option A: Auto-Sync (Recommended)

*Requires Desktop Chrome or Edge.*

1. **Start Syncing**
   *   On the Dashboard, find the **"Auto-Sync Uploader"** box.
   *   Click **"Select TDF to Auto-Sync"**.
   *   Select the active \`.tdf\` file generated by TOM for your tournament.

2. **Monitoring Status**
   *   Look for the **"Live Syncing"** indicator with a pulsing green light.
   *   **Do NOT refresh the page.** Refreshing will stop the sync. If this happens, simply re-select the file.
   *   The system will automatically detect when you "Save" in TOM and upload the changes within 5 seconds.

### Option B: Manual Upload

If Auto-Sync fails or if you are using an unsupported browser:

1. **Upload Manually**
   *   Click the same **"Select TDF to Auto-Sync"** button.
   *   Select your \`.tdf\` file.
   *   The file is uploaded immediately upon selection. You can do this at the end of every round to update the online standings manually without keeping the sync running.

---

## Chapter 5: Player Experience (What to tell players)

**Direct Players:** Tell players to scan the QR code to find their table numbers.

1. **Find Me (Yellow Highlight)**
   *   When a player logs in and views the pairings, **their own row will be highlighted in yellow**. They don't need to search through the entire list.

2. **Live Updates (Realtime)**
   *   Tell players: "The page updates automatically. **You do NOT need to refresh.**"
   *   As soon as you save/upload the data in TOM, their phones will show the new round or standings within seconds.
`;

const ZH_MANUAL = `
# 主办方用户手册

**角色：** 主办方与工作人员
**版本：** 1.0
**日期：** 2026-01-26

---

## 第一章：入门指南（账户设置）

**背景：** 系统需要进行一次性的“强制入职流程”，以便将您的账户与玩家 ID 关联，用于赛事汇报。

1. **通过 Google 登录**
   *   点击“登录”按钮，使用您的 Google 账户登录。

2. **重定向至入职页面**
   *   首次登录时，系统会自动将您重定向至“欢迎来到 TCG Manager”入职页面。

3. **完成个人资料**
   *   **姓名（First/Last Name）：** 确认您的姓名无误。
   *   **宝可梦玩家 ID（Pokemon Player ID）：** 输入您的 7 位数玩家 ID（导出 TDF 文件时必需）。
   *   **出生年份（Birth Year）：** 从下拉菜单中选择您的出生年份，以确定您的年龄组别。

4. **访问仪表板**
   *   点击“完成个人资料（Complete Profile）”。系统将重定向至主仪表板，您可以在此管理赛事。

---

## 第二章：赛前准备（第一轮之前）

**设置：** 在主页选择您的赛事，进入特定的赛事仪表板。

### 名单管理

使用屏幕右侧的 **名单管理（Roster Management）** 卡片来登记玩家。

1. **搜索玩家**
   *   在“添加新玩家（Add New Player）”区域，在搜索栏中输入姓名或玩家 ID（例如“Pikachu”或“1234567”）。
   *   点击搜索图标（放大镜）或按回车键。

2. **添加玩家至名单**
   *   在结果列表中找到正确的玩家。核对他们的 ID 和出生年份。
   *   点击玩家姓名旁边的 **“+”（添加用户）** 按钮。系统会显示成功提示（“Added [Name] to roster”）。

3. **未找到玩家**
   *   如果系统提示“未找到符合条件的资料（No eligible profiles found）”，则该玩家可能尚未创建账户或其资料不完整。
   *   **操作：** 请玩家在其设备上登录并完成第一章的入职步骤。完成后，再次搜索该玩家。

---

## 第三章：打印物料（赛事套件）

**传单：** 为您的场馆生成专业的二维码海报，让玩家可以即时查看配对和排名。

1. **访问传单页面**
   *   在赛事仪表板上，点击右上角的黑色按钮 **“打印二维码海报（Print QR Poster）”**。

2. **打印 PDF**
   *   系统将打开一个名为“实时配对（Live Pairings）”的新页面，其中包含一个大二维码。
   *   点击顶部的 **“打印此页（Print This Page）”** 按钮。
   *   *提示：* 将打印机设置为 **A4/Letter 纸张**、**纵向**和 **100% 缩放**。页眉和页脚将自动隐藏。

---

## 第四章：举办赛事（实时同步）

**工作流程：** 此 App 通过 TDF 文件直接从您的 TOM（赛事运营管理）软件可视化数据。

### 选项 A：自动同步（推荐）

*需要桌面版 Chrome 或 Edge 浏览器。*

1. **开始同步**
   *   在仪表板上，找到 **“自动同步上传器（Auto-Sync Uploader）”** 框。
   *   点击 **“选择要自动同步的 TDF（Select TDF to Auto-Sync）”**。
   *   选择由 TOM 为您的赛事生成的活动 \`.tdf\` 文件。

2. **监控状态**
   *   查看带有绿色脉冲灯的 **“实时同步中（Live Syncing）”** 指示器。
   *   **请勿刷新页面。** 刷新会停止同步。如果发生这种情况，请重新选择文件即可。
   *   系统会自动检测您在 TOM 中的“保存”操作，并在 5 秒内上传更改。

### 选项 B：手动上传

如果自动同步失败或您使用的是不受支持的浏览器：

1. **手动上传**
   *   点击同一个 **“选择要自动同步的 TDF（Select TDF to Auto-Sync）”** 按钮。
   *   选择您的 \`.tdf\` 文件。
   *   文件选中后会立即上传。您可以在每一轮结束时执行此操作，以手动更新在线排名，而无需保持同步运行。

---

## 第五章：玩家体验（告知玩家的内容）

**引导玩家：** 告诉玩家扫描二维码以查找他们的桌号。

1. **找到我（黄色高亮）**
   *   当玩家登录并查看配对时，**他们自己的一行将以黄色高亮显示**。他们无需在整个列表中搜索。

2. **实时更新**
   *   告诉玩家：“页面会自动更新。**不需要刷新。**”
   *   一旦您在 TOM 中保存/上传数据，他们的手机将在几秒钟内显示新一轮比赛或排名。
`;

export default function OrganizerHelpPage() {
    return (
        <div className="container max-w-4xl py-8 space-y-8">
            <div className="flex items-center gap-4">
                <Link href="/" className="text-muted-foreground hover:text-foreground">
                    <ArrowLeft className="w-5 h-5" />
                </Link>
                <div>
                    <h1 className="text-2xl font-bold tracking-tight">Organizer Manuals</h1>
                    <p className="text-muted-foreground">Guides and documentation for tournament organizers.</p>
                </div>
            </div>

            <Tabs defaultValue="en" className="w-full">
                <TabsList className="mb-4">
                    <TabsTrigger value="en">English (US)</TabsTrigger>
                    <TabsTrigger value="zh">Chinese (中文)</TabsTrigger>
                </TabsList>

                <TabsContent value="en">
                    <Card>
                        <CardHeader>
                            <CardTitle>Organizer User Manual</CardTitle>
                            <CardDescription>Comprehensive guide for running tournaments.</CardDescription>
                        </CardHeader>
                        <CardContent className="prose dark:prose-invert max-w-none">
                            <ReactMarkdown>{EN_MANUAL}</ReactMarkdown>
                        </CardContent>
                    </Card>
                </TabsContent>

                <TabsContent value="zh">
                    <Card>
                        <CardHeader>
                            <CardTitle>主办方用户手册</CardTitle>
                            <CardDescription>赛事举办综合指南</CardDescription>
                        </CardHeader>
                        <CardContent className="prose dark:prose-invert max-w-none">
                            <ReactMarkdown>{ZH_MANUAL}</ReactMarkdown>
                        </CardContent>
                    </Card>
                </TabsContent>
            </Tabs>
        </div>
    );
}
